name: Deploy Web Components

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build:wc

      # copia a versÃ£o do package.json
      - name: Get package version
        id: pkg
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      # cria pastas versionadas e latest
      - name: Prepare dist
        run: |
          mkdir -p publish/wc/${{ steps.pkg.outputs.version }}
          mkdir -p publish/wc/latest
          cp -r dist/wc/* publish/wc/${{ steps.pkg.outputs.version }}/
          cp -r dist/wc/* publish/wc/latest/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
